CREATE TABLE emprestimos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataEmprestimo DATE NOT NULL,
    dataDevolucao DATE NOT NULL,
    status VARCHAR(50) NOT NULL,

    usuario_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,

    CONSTRAINT pk_emprestimos PRIMARY KEY (id),

    CONSTRAINT fk_emprestimos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_emprestimos_livro FOREIGN KEY (livro_id) REFERENCES livros (id)
);